from .main_routes import main_routes
from .auth_routes import auth_routes
from .users_routes import users_routes
from .audit_routes import audit_routes
from .ordenes_routes import ordenes_routes
from .terrenos_routes import terrenos_routes
from .campanias_routes import campanias_routes
from .roles_routes import roles_routes
from .profile_routes import profile_routes
from .maquinaria_routes import maquinaria_routes
from .prediccion_routes import prediccion_routes
from .cultivo_routes import cultivo_routes  
from .empresas_routes import empresas_routes